site_name: Teach Docs
site_description: Documentation powered by MkDocs Material
site_url: https://univpier.github.io/teach/

theme:
  name: material

nav:
  - Home: index.md
  - Lesson 1: lesson-1.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
